### ISSUE TITLE
Add option to upload images without Inspector

### ISSUE THREAD

**Issue by Loenike** [Passiolife/passio_devops#10]
@Loenike commented on [Fri Mar 06 2020](https://github.com/Passiolife/bulk_inspector/issues/6)

### Add option to upload images without Inspector

Currently, the only way to add images into our dataset (database+assets) is via Inspector.

For some images, where we don't need to review or tag (at the moment, this just applies to background images, but could be relevant for canonical images as well, or side projects), it would be good to have an option to add data WITHOUT using Inspector - else, we always depend on finding an empty slot in the Inspector queue and upload the images to Inspector + manually purge the Inspector queue. That's a work around, but not ideal.

Maybe we could have a separate bucket and once we drop files there, the automatic upload starts (same as for the Inspector bucket) - but skipping the actual review in Inspector.

---

@drstarson commented on [Fri Mar 06 2020](https://github.com/Passiolife/bulk_inspector/issues/6#issuecomment-595907483)

> Maybe we could have a separate bucket and once we drop files there, the automatic upload starts (same as for the Inspector bucket) - but skipping the actual review in Inspector.

Yes, this is very similar to the project we are asking our backend candidates to complete https://github.com/Passiolife/go-terra-test

The only open question is how/what to write as associated data and how to assign labels. We need to at least be able to define the name of the visual group: maybe via folder name?

---

@brandonparis commented on [Sun Mar 08 2020](https://github.com/Passiolife/bulk_inspector/issues/6#issuecomment-596220368)

Defining a separate folder makes sense. It could have a separate Cloud Function that triggers on-upload and does different things than the Inspector.

---

@Loenike commented on [Mon Mar 09 2020](https://github.com/Passiolife/bulk_inspector/issues/6#issuecomment-596642708)

> The only open question is how/what to write as associated data and how to assign labels. We need to at least be able to define the name of the visual group: maybe via folder name?

We will need to modify the API for both this and the current Inspector with the ability to assign both `labelname` and `datasetid` together with the upload inside the API. This is currently done with a workaround in the `data_client` and `inspector_tools`, but we definitely need to include it in the API itself.

The current setup stores data before the actual upload to the Inspector starts in the `passio_data_staging` bucket in the format: folders named `PASSIOID_DATASETID` containing images for that passioID and that datasetid, e.g. `VEG0018_SEGM0001`. I'll open a separate issue for that.

---

@drstarson commented on [Tue Mar 24 2020](https://github.com/Passiolife/bulk_inspector/issues/6#issuecomment-597996127)

O.k.! Agreed. 

One question is: does it have to be the same microservice? Or can we write a completely separate API from scratch that does what we need it to do? 

Let's say we start MediaAgelity tomorrow. I believe it would be 100x easier/faster/cleaner to tell them: we need an API end-point that performs a set of functions. 

LMK if I'm missing something important. Is there a reason to do everything from the same microservice? Or can we go with keeping our current API (the one created by Tim) and adding a new API to do tasks not currently covered by the current API. Eventually, we can migrate 100% to the new API. 

- [x] @brandonparis  @Loenike Please LMK your thoughts.

**Comment by Loenike** [comment]
I believe the setup will look similar to this:

- **passio-dev-env-staging-direct** bucket with folders indicating the labelID_sourceID (passioID_datasetid in the old terminology) 
- we can discuss how we want to "start" the upload or schedule it to start once a day, but those images would be uploaded to the bucket **passio-dev-env-assets-original-direct**
- this triggers the assets service to start the transform/ingest process
- since we know that the labelID of those images is correct and applies to the entire images, we do not need any inspection by Inspector and we want to SKIP this part of the pipeline
- we need to assure that the states are set correctly, so that after adding the assets to the database, the cropping action takes place

**Comment by brandonparis** [comment]
Adding a new microservice for this sounds good to me.

**Comment by Loenike** [comment]
Done.
