### ISSUE TITLE
Create migration script for data migration

### ISSUE THREAD

**Issue by Loenike** [Passiolife/passio_devops#14]
### Create migration script for data migration

Once we have the dev-env database setup https://github.com/Passiolife/passio_devops/issues/3 and are sure we are not going to introduce mayor changes anymore, we need to setup the migration script for the database content + assets files on the passio-nutrition-develop project to the dev-env // production environment.

These points are just first brainstorming items. I will need to detail those out and add more.

**Metadata**
- recalculate metadata for the assetids where we do not yet have the metadata
- ~calculate the metadata for the cropped assets~ deprecated, cropped assets are downsized and thus always have 224x224 height/widht. easy to include at a later stage without main changes in structure
- the originalsize for some assets is still included in the assets table instead of the metadata table
- since we are not really using the metadata table at the moment..

**Flags**
- We don't want to loose the information about the assigned flags (excluded or not mainly). However, since in the current setup we do NOT have a unique identifier for a region, there are some constraints to tracing back the flag.
- we can easily create a list of `assetid` + `index` + `labelname` + `flag`
- given that list, we can successfully assign the flag to a new regionid:
a) if there is only one region with label X for a given assetid
b) if there is more than one region with label X for a given assetid, if all those regions have been assigned the SAME flag
c) in all other cases, we need to probably assign a new flag "migration_review" and redo the review in bulk inspector after the migration

**Comment by drstarson** [comment]
> c) in all other cases, we need to probably assign a new flag "migration_review" and redo the review in bulk inspector after the migration

Do you have a feeling for the scale of this? How many regions would need to be reviewed?

**Comment by Loenike** [comment]
Updating the status:

- we have 256k regions that are "small" which means either height or width is below 224px
- we have 402k regions that are accepted (manually approved)
- we have 129k regions that are unreviewed (we never cropped nor reviewed them)
- we have 103k regions that we will need to revisit because of the migration
- we have 35k regions that we excluded
