### ISSUE TITLE
Set regions flag to locked when asset is in Inspector

### ISSUE THREAD

**Issue by Loenike** [Passiolife/passio_devops#17]
### Set regions flag to locked when asset is in Inspector

- [ ] Add an API endpoint if necessary or reuse: https://github.com/passiolife/bulk_inspector/issues/27
 
- [ ] include the call of that API endpoint into microservice/assets service:

If an assetid is pushed to the Inspector queue, the state of all regions corresponding to that assetid should be set to `locked`.

- [ ] @sptrakesh review and LMK if anything is unclear

**Comment by Loenike** [comment]
@sptrakesh Does this sufficiently cover your concern? 

> @Loenike for #4 above, we could use a locked status flag. When user selects a region for edit, we lock the region. Will probably need to build in some kind of lock expiration policy as well, to guard against errors (user or software) leading to region being locked, and then needing manual database update intervention.

**Comment by sptrakesh** [comment]
@Loenike I think so.  I started a wiki page to discuss our options and strategies.  Let us capture all thoughts on the wiki, and then we can roll that up into the implementation of this issue.

https://github.com/Passiolife/passio_devops/wiki/Locking-strategies

**Comment by drstarson** [comment]
I think the `Optimistic Lock` strategy is the way to go because there is low likelihood of resource contention. But I might be missing something important. @Loenike, your call.

**Comment by Loenike** [comment]
@sptrakesh  After reviewing the wiki, I think we should definitely go the path of least resistance. Let's review together the workflow and how we plan to assign separate states to both assets and regions - I think after that, we have a clearer picture if we actually need a Lock/Optimistic Lock OR if we can just define the workflow in such a way that prevents automatically by design any type of double-edits/complications.

> If there is a standard workflow that can be assumed, we could use the *state* of an asset to determine if certain applications are allowed to modify the asset or not.  For instance, if we know that when an asset enters the system, an event handler function will always perform some operation on the asset, and then move it to another state, we could prohit all other applications from modifying the asset until it enters that *state*.  Like with locking, this could cause the asset to be unmodifiable (locked) if the event handler fails for some reason.  Proper error reporting can mitigate that to some extent.

**Comment by sptrakesh** [comment]
@Loenike yes, let us meet again to finalize the plan.  Can you compose a simple schematic of just that part of the workflow, and we can use that as subject of what we discuss and design for.

**Comment by drstarson** [comment]
@Loenike I'm happy to review the above if it helps.

**Comment by Loenike** [comment]
Adding some descriptions:

We need 3 separate states for assets:
- **added** the asset has been added to the dataset, but 
- **inspecting** the asset is in the dataset, and currently in the pubsub Inspector queue
- **processed** the asset is in the dataset, and not in the Inspector queue

We need 4 different states for regions:
- **locked**
- **unreviewed**
- **accepted**
- **excluded**

Please review this small diagram that I added:
https://app.diagrams.net/?page-id=NSHsnWJDVLWjml2kUFzy#G1O-B7AprLraZCO-Y9w18juEJC_j2R8Fkh

**Comment by sptrakesh** [comment]
@Loenike I am unable to access the diagram.

**Comment by Loenike** [comment]
@sptrakesh can you try to access with your passiolife email?

**Comment by sptrakesh** [comment]
@Loenike that is what I did.  I authorized access to google drive etc. as prompted, but at the end I got a message saying file does not exist.

**Comment by Loenike** [comment]
Ok, sorry for that. Super weird, if I click on the link, I can access and the settings are set correctly - in theory ...
Try with this one instead, you'll need to navigate though to the tab **states_diagram**
https://drive.google.com/file/d/1O-B7AprLraZCO-Y9w18juEJC_j2R8Fkh/view?usp=sharing

**Comment by drstarson** [comment]
<img width="708" alt="Screen Shot 2020-04-12 at 9 03 52 PM" src="https://user-images.githubusercontent.com/17357591/79091186-307a9280-7d01-11ea-8944-68b1e7484b43.png">

- [ ] @Loenike @sptrakesh Should there be two different Pub/Subs?

**Comment by Loenike** [comment]
I don't have a preference here. I just thought it would make sense to have the same pubsub, since this part of the pipeline is exactly the same in both cases - unless I am overseeing something. The only difference to these 2 cases is that in the left case, we push the asset after the first part to another pubsub (inspector queue). 

@sptrakesh what's your opinion on this?

**Comment by sptrakesh** [comment]
If we have a single pub-sub then the process(es) need to be aware of which environment/API to use for operations.  If the message payload has enough context/information, it may be possible, but it does involve adding some `if/else` type logic.

Simpler (and better) from a code perspective would be to not have to worry about such details and always perform the desired actions without knowing anything about the target environment.

A single Pub/Sub may  be easier from a set up perspective, especially when done manually.  From a Terraform perspective, it may be be easier to have each environment be totally self sufficient.

**Comment by Loenike** [comment]
Ok, let's have 2 separate pub-subs then. Sounds to me as the better aligned approach.

**Comment by drstarson** [comment]
Agreed. I think 2 pub-subs is cleaner.

**Comment by Loenike** [comment]
Done.
