### ISSUE TITLE
Decide how to use the locked flag

### ISSUE THREAD

**Issue by Loenike** [Passiolife/passio_devops#18]
### Decide how to use the locked flag

If a region is locked, how do we use that information? 

Options:

- Exclude them from display in Bulk Inspector
- Do not allow any modifications on those regions by the Bulk Inspector
- We do need to allow a delete modifications on those regions by the Inspector

@sptrakesh your call on best practices here

**Comment by sptrakesh** [comment]
I will document standard locking strategies and open that up for discussion.

**Comment by Loenike** [comment]
Done.
