### ISSUE TITLE
Add function/microservice to crop regions

### ISSUE THREAD

**Issue by Loenike** [Passiolife/passio_devops#19]
### Include the action of cropped regions

The action should:
- crop all regions for a given assetid and downsize them to 224x224
- store them in the cropped assets bucket with the storageurl defined in the database

This action can be called by:

- the inspector queue when processing a message and thus saving new regions to the database
- when uploading data to the database/assets bucket SKIPPING the inspector

Might be a duplicate issue to this here: https://github.com/Passiolife/bulk_inspector/issues/14

@sptrakesh Not sure if we want to handle this via microservice/cloud function...

**Comment by sptrakesh** [comment]
@Loenike how are we currently resizing images - imagemagick?

**Comment by Loenike** [comment]
both cropping and resizing with python PIL library:

cropping:
https://github.com/Passiolife/data_client/blob/630ce3c0341cc1db5af59926eeaab450c501f262/data_client/image_utils.py#L107

resizing:
https://github.com/Passiolife/ClassificationAIPlatform/blob/master/Preprocessing%20Steps.ipynb

**Comment by drstarson** [comment]
@Loenike for resizing you linked the notebook, are we doing resizing by running the notebook manually? 

@sptrakesh If we have both features as self-contained .py functions, we should be able to implement those as CloudFunctions, right?

**Comment by sptrakesh** [comment]
Yes, it should be possible to convert the existing code into functions.

**Comment by Loenike** [comment]
> @Loenike for resizing you linked the notebook, are we doing resizing by running the notebook manually?

Yes, we currently are. The resizing is part of the preprocessing steps before we can start the CL Training.

**Comment by Loenike** [comment]
Done.
