### ISSUE TITLE
setup dev project on GCP

### ISSUE THREAD

**Issue by drstarson** [Passiolife/passio_devops#2]
- [x] @drstarson  to setup a dev env as a new project on GCP via terraform and keep tf files in this repo

- [x] add env diagram and overview + quick video / add to the wiki

**Comment by drstarson** [comment]
Here is the link to the project:
https://console.cloud.google.com/home/dashboard?organizationId=956474187305&project=passio-dev-env&supportedpurview=project

**Comment by drstarson** [comment]
Here is the current state of the diagram: 
https://drive.google.com/file/d/1O-B7AprLraZCO-Y9w18juEJC_j2R8Fkh/view?usp=sharing

I think we should take the following approach: 

1. Create a diagram and a full layout / architecture of the backend we need
2. Treat passio_nutrition_develop as product for now and just ignore everything that is not relevant
3. In parallel build a the implementation of the desired architecture from item 1 in the passio_dev_env project on GCP. We can use truncated versions of the datasets and a dev database. 
4. Promote the dev env project into a new production project and migrate full scale datasets and databases there from passio_nutrition develop and from bpi project. 
5. Deprecate passio_nutrition_develop and bpi_project. With that deprecation we will remove all the unused stuff. 

- [ ] @Loenike please review and edit
- [ ] @brandonparis please review and edit
- [ ] @sptrakesh please review and edit

**Comment by Loenike** [comment]
I think this approach makes sense.

> Create a diagram and a full layout / architecture of the backend we need

I edited the draw.io diagram.

> Deprecate passio_nutrition_develop and bpi_project. With that deprecation we will remove all the unused stuff.

Just to be sure: This means, that we would have our entire pipeline on the dev env project + production project? Which means, not only the collection/tagging part (Inspector - Bulk Inspector), but also the machine learning part of the pipeline?

I think at the moment the `bpi-project` is some sort of "host project" for the `passio-nutrition-develop` project - this is why the Stackdriver Monitorning runs on the `bpi-project` and there seems to be a VM on `bpi-project` linked to Inspector App Engine (which itself is on the `passio-nutrition-develop`)

**Comment by drstarson** [comment]
> Just to be sure: This means, that we would have our entire pipeline on the dev env project + production project? Which means, not only the collection/tagging part (Inspector - Bulk Inspector), but also the machine learning part of the pipeline?

Right! You and James can decide whether to keep ML in the same project or create a new project.

**Comment by Loenike** [comment]
Done.
