### ISSUE TITLE
Enable private IP for database

### ISSUE THREAD

**Issue by sptrakesh** [Passiolife/passio_devops#26]
Please enable private IP for the development database.  This seems to be the preferred method for enabling connectivity from cloud compute instances to the database.

**Comment by drstarson** [comment]
- [ ] @sptrakesh Done. Please check and re-open if I misunderstood the request.

**Comment by Loenike** [comment]
FYI: I deleted the `postgres-develop` instance - this was just for trying out things.

**Comment by drstarson** [comment]
@Loenike Great! This is a very good practice to remove everything we are not using.
