### ISSUE TITLE
setup dev database in the dev env project

### ISSUE THREAD

**Issue by drstarson** [Passiolife/passio_devops#3]
- [x] @Loenike setup a dev database in the dev env project 

- [x] @Loenike please check liquibase for database structure versioning

Please ping @sptrakesh if you have questions on this
CC @brandonparis

**Comment by Loenike** [comment]
@sptrakesh 

We now have the dev env database in place:

`postgres-develop` - `34.70.109.244`

https://console.cloud.google.com/sql/instances/postgres-develop/overview?project=passio-dev-env&organizationId=956474187305&duration=PT1H

CREATE script
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE sources (sourceid UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
sourcename char (8) UNIQUE,
description text,
license varchar);

CREATE TABLE states (stateid UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
statename varchar UNIQUE,
description text);

CREATE TABLE types (typeid UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
typename varchar UNIQUE,
description text);

CREATE TABLE assets (assetid UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
storageurl varchar UNIQUE,
originalmd5 varchar UNIQUE,
sourceid UUID REFERENCES sources(sourceid),
deleted boolean DEFAULT FALSE,
created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
metadata json DEFAULT '{"originalheight":0,"originalwidth":0,"originalsize":0}');

CREATE TABLE labels (labelid UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
labelname char (7) UNIQUE,
displaylabelname varchar UNIQUE,
description text,
typeid UUID NOT NULL REFERENCES types(typeid),
trained boolean DEFAULT FALSE,
candidate boolean DEFAULT FALSE,
insufficient boolean DEFAULT FALSE);

CREATE TABLE assetstates (id UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
assetid UUID NOT NULL REFERENCES assets(assetid),
stateid UUID NOT NULL REFERENCES states(stateid),
userid varchar NOT NULL DEFAULT 0,
created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE regions (regionid UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(), 
assetid UUID NOT NULL REFERENCES assets(assetid),
rectangle json NOT NULL DEFAULT '{"xmin":0,"xmax":1,"ymin":0,"ymax":1}',
labelid UUID NOT NULL REFERENCES labels(labelid),
storageurl varchar UNIQUE);

CREATE TABLE regionstates (id UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
regionid UUID NOT NULL REFERENCES regions(regionid),
state UUID NOT NULL REFERENCES states(stateid),
userid varchar NOT NULL,
created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);
```

Missing items for @Loenike:

- [ ] adjust few things in the data_model to match the database setup

- [ ]  add example data to the database to match the example files in the buckets

**Comment by Loenike** [comment]
- [ ] @sptrakesh please review and LMK if you spot any inconsistency

- [ ] @sptrakesh liquibase setup

- [ ] @Loenike get familiar with liquibase

**Comment by sptrakesh** [comment]
@Loenike I would create a dedicated user that the API (and any other script of similar) would use to connect to the database, and also a designated schema in which we create the tables.

```
create user asset_user with password '<some suitable password>';
drop schema if exists assets cascade;
create schema if not exists assets;
alter schema assets owner to asset_user;
```

Will need to prefix the schema name for all tables - eg. `assets.sources`.

After all table statements, we can also add:

```
grant all on all tables in schema assets to asset_user;
grant all on all functions in schema assets to asset_user
```

**Comment by Loenike** [comment]
@sptrakesh We have the "default" user that is defined automatically by GCP (with a password) - I am using these credentials when accessing via PSequel. 

Would you recommend an additional user profile?

**Comment by sptrakesh** [comment]
@Loenike not sure if `assets` is a good schema name.  Ideally it should be the name of the current project - maybe @drstarson can come up with a nice name.

**Comment by sptrakesh** [comment]
> @sptrakesh We have the "default" user that is defined automatically by GCP (with a password) - I am using these credentials when accessing via PSequel.
> 
> Would you recommend an additional user profile?

@Loenike yes.  The default user is probably the `postgres` *root* user account.  We definitely do not want to use that from any deployed application code.

**Comment by Loenike** [comment]
Ok, I'll adjust and create a new user.

Also, yes. `assets` is the name of the `database` itself, which means we should definitely avoid using it for the `schema`. We might even choose a different name for the entire database, since `assets` is a table inside the database.

@brandonparis once I have fixed those, I'll share the credentials with you as you requested

**Comment by sptrakesh** [comment]
@Loenike it would be better to use `jsonb` instead of `json` as the column type.

"There are two JSON data types: json and jsonb. They accept almost identical sets of values as input. The major practical difference is one of efficiency. The json data type stores an exact copy of the input text, which processing functions must reparse on each execution; while jsonb data is stored in a decomposed binary format that makes it slightly slower to input due to added conversion overhead, but significantly faster to process, since no reparsing is needed. jsonb also supports indexing, which can be a significant advantage."

**Comment by Loenike** [comment]
**Update:**

- I changed all json data to data type `jsonb`
- database is called `passio` with the schema called `assets` - I added a new user `assets_user` (@sptrakesh we might need to check if the permissions for that `assets_user` are all set correctly)
- I added all relevant files to the `/sql` directory in the `data_model` repo



FYI outlook:
- we will store nutrition data inside a separate schema `nutrition` inside the `passio` database
- we can have a separate schema `models` in the same database, with information about the AI models
- I tested/confirmed that we can create cross-schema FK relationships

**Comment by Loenike** [comment]
Data Model:

**Comment by Loenike** [comment]
Done.
