### ISSUE TITLE
logic for triggering the crop function

### ISSUE THREAD

**Issue by Loenike** [Passiolife/passio_devops#39]
**logic for triggering the crop function**

- Every time an assetid is completed by Inspector, we are setting the **state** of that assetid to **inspected**. (@brandonparis please confirm that this is part of Inspector already)

- This should trigger the cropping function. Inside that cropping function, we agreed to set the state of the assetid to processed, and the region state to unreviewed, once the cropping function has succeeded.

Please LMK if more information is required on this.

**Comment by sptrakesh** [comment]
@Loenike is this supposed to be near realtime or more of a batch process?  Trying to understand what the requirement is from an implementation perspective.

**Comment by Loenike** [comment]
near realtime is my suggestion

**Comment by ncheikh-passio** [comment]
The http function that will trigger this process is ready.

This PR sets up the etcd config: https://github.com/Passiolife/passio_devops/pull/40

**Comment by Loenike** [comment]
Done.
