### ISSUE TITLE
Setup the dev database with a replica

### ISSUE THREAD

**Issue by drstarson** [Passiolife/passio_devops#7]
- [ ] @sptrakesh following your comment in #4 I suggest we start testing HA and DB replica setups in the dev env. Can you set it up for the current dev db?

**Comment by sptrakesh** [comment]
@drstarson it is possible to convert the current database to a HA cluster.  It requires a database server restart however, so it needs to be coordinated to ensure all using applications are restarted as necessary.  Not sure if the connection managers for individual applications/services will auto recover the connection.

**Comment by sptrakesh** [comment]
@drstarson rethinking the current environment.  I tested adding a read replica to the current database (destroyed it after test), and it is a non-intrusive process.  I think we can survive with a read replica that we can promote to master should the need arise, and set up the new `dev` and eventual `prod` environments with the database as a HA service.

**Comment by drstarson** [comment]
Great! So we are going without replica for now, but can add if needed, right? If yes, and there is no addition action needed, please close this one.

**Comment by sptrakesh** [comment]
Read replicate created for current, which will act as a hot-standby.  Does ensure minimal data loss (backup is only once per day), should the master fail for any reason.

For new environments, we will set up HA cluster, which will provide for auto failover service by GCP.
