### ISSUE TITLE
Ensure consistency of cropped-assets bucket

### ISSUE THREAD

**Issue by Loenike** [Passiolife/passio_devops#9]
### Ensure consistency between assets and cropped-assets bucket

> It sounds like we need to think through and add consistency checks to make sure assets and cropped-assets are synced. For example, if we change a few tags for cropped images via Bulk Inspector we need to propagate those changes into the assets and reflect them in the non-cropped images.
> Similarly, if we are changing a bbox or deleting bbox via the main Inspector, we need to propagate those changes into the cropped assets.

Once an image has been processed/ingested by the assets service, and is stored in the assets bucket, there won't be any change to that asset in the assets bucket. This means, the **consistency**  needs to be ensured between the **cropped-assets** bucket and the **regions** table where we specify the information related to a region.

We will need to track things by using specific states for an asset:
- state A means: the regions on that asset will be modified soon. This should cause the following actions:
- ~DELETE the cropped assets related to that assetid in the cropped assets bucket~ **deprecated, we do periodically delete of deprecated cropped images**
- mark the entries in the database for those regions with a specific state Y - so that we know that they are currently being modified and NOT available **LK UPDATE: this is the `locked` flag**
- ~this state A can be triggered by the bulk inspector before doing a reassignment~ **no need for this** OR by the inspector when pushing existing assets back into the inspector queue. ~Both actions represent the asset being "in process/review"~ **bulk inspector does not modify the bboxes - different type of review**
________
- state B means: we added new regions for a specific assetid
- CROP the regions and save them to the cropped-assets bucket
- update the state in the regions table for those regions to reflect that they are unreviewed
- ~this state B can be triggered by the bulk inspector AFTER doing the reassignment~ **no need for this** OR by the inspector queue when processing a message and thus saving the new regions to the database OR by the assets service when uploading data to the database/assets bucket SKIPPING the inspector

_____
@sptrakesh let's discuss this in detail, we can use the state concept of the data model for this

**Comment by Loenike** [comment]
After speaking with James, we agreed that we will have the cropped images in a flat bucket without keras format - and without the filepaths including some sort of metadata. All metadata is stored in the `regions` table.

We can separate between the following actions:

1. Reassigning the label of cropped images - this is driven inside bulk inspector and will only change the metadata inside the `regions` table - no change inside the bucket.

2. Changing the flag of cropped images - this is driven inside bulk inspector and will only change the metadata inside the `regions` table - no change inside the bucket.

3. The only action when we need to **modify** something in the cropped images bucket, is when we are actually REINSPECTING an image inside the INSPECTOR. 

4. In order to avoid double edit actions on a region, I believe we need to flag regions that are currently in the Inspector. That way, we can assure to either exclude them from the bulk inspector display or not allow to edit them.

**Comment by sptrakesh** [comment]
@Loenike for #4 above, we could use a `locked` status flag.  When user selects a region for edit, we *lock* the region.  Will probably need to build in some kind of *lock expiration* policy as well, to guard against errors (user or software) leading to region being locked, and then needing manual database update intervention.

**Comment by Loenike** [comment]
Locked status flag is a good option.

Regarding _lock expiration policy_ - let's discuss this in detail. The inspector pub sub queue itself is "clearing" itself after 7 days with the current setup - we could use that expiration of the pub sub also for unlocking the locked boxes, since the "unlocking" will be happening when a message is acknowledged in pubsub. We definitely need to make sure that any _lock expiration policy_  is handling inspector pubsub and locking of the regions in a consistent way

**Comment by sptrakesh** [comment]
@Loenike yes let us use the next meeting to discuss this.  I do not have a clear picture of when a region is locked, and who is responsible for unlocking.

**Comment by drstarson** [comment]
- [ ] @Loenike @sptrakesh did you address this? I think this is a very important issue to be aligned.

**Comment by Loenike** [comment]
I think we resolved the question on Friday.  I added separate tickets for all items mentioned in this issue and linked them here. We can summarize:

> 1. Reassigning the label of cropped images - this is driven inside bulk inspector and will only change the metadata inside the regions table - no change inside the bucket.

defined in here: https://github.com/Passiolife/bulk_inspector/issues/25

> 2. Changing the flag of cropped images - this is driven inside bulk inspector and will only change the metadata inside the regions table - no change inside the bucket.

defined in here: https://github.com/Passiolife/bulk_inspector/issues/27

> 3. The only action when we need to modify something in the cropped images bucket, is when we are actually REINSPECTING an image inside the INSPECTOR.

We do NOT need to modify anything inside the cropped images bucket, we decided to keep the deprecated crops and delete periodically: https://github.com/Passiolife/passio_devops/issues/15#issuecomment-606037202

We do need to add the new crop into the bucket: https://github.com/Passiolife/passio_devops/issues/19

> 4. In order to avoid double edit actions on a region, I believe we need to flag regions that are currently in the Inspector. That way, we can assure to either exclude them from the bulk inspector display or not allow to edit them.

- pushing an assset to inspector pub sub should set the flag of all bounding boxes inside that asset to `locked` #17  - this issue includes the discussion of a "lock expiration policy" 
- acknowledging an asset in inspector pub sub should set the flag of all bounding boxes inside that asset to `unreviewed` #16 
- decide how to use the lock flag: https://github.com/Passiolife/passio_devops/issues/18

**Comment by Loenike** [comment]
I'll push this issue to Review/QA - I think we covered all items in separate tickets.

**Comment by drstarson** [comment]
@Loenike Great summary!
